mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    # 配置数据源
    #driver-class-name: com.mysql.jdbc.Driver

    driver: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456


  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**

  thymeleaf:
    prefix: classpath:/templates/ # 不加，使用默认配置也行
    suffix: .html # 不加，使用默认配置也行
    encoding: UTF-8
    cache: false # 开发环境关闭缓存
    mode: LEGACYHTML5 # 执行thymeleaf非严格html模式

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/








